/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/intelligenceapi/meat-hygiene/national": {
    get: operations["GetNationalScore"];
  };
  "/intelligenceapi/meat-hygiene/establishments": {
    get: operations["GetEstablishmentsScore"];
  };
}

export interface definitions {
  Score: {
    metadata_period_in_days?: number;
    establishment_id?: number;
    total_active_breaches?: number;
    total_active_reported_concerns?: number;
    total_species?: number;
    total_establishments?: number;
    establishment_name?: string;
    percentage_total_hygiene_score?: number;
    metadata_date_end?: string;
  };
}

export interface operations {
  GetNationalScore: {
    responses: {
      /** One fortnights worth of score */
      200: {
        schema: {
          data?: definitions["Score"][];
        };
      };
    };
  };
  GetEstablishmentsScore: {
    parameters: {
      query: {
        /** Filter to only chosen establishment ids */
        ids?: number[];
      };
    };
    responses: {
      /** One fortnights worth of score */
      200: {
        schema: {
          data?: definitions["Score"][];
        };
      };
    };
  };
}

export interface external {}
